/**
 * useImport Hook
 *
 * Reusable logic for importing dashboards and widgets from JSON files
 * Handles file selection, validation, and Redux actions
 */

import { useRef, type ChangeEvent } from 'react';
import { useAppDispatch } from '@/store/hooks';
import { importDashboard, addWidget } from '@/store';
import {
  readJSONFile,
  validateDashboardImport,
  validateWidgetImport,
} from '@/utils/import';

export function useImport() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const dispatch = useAppDispatch();

  const handleFileSelect = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    try {
      const json = await readJSONFile(file);

      // Try dashboard import first
      const dashboardResult = validateDashboardImport(json);
      if (dashboardResult.success) {
        const confirmed = window.confirm(
          `Import dashboard "${dashboardResult.data.name}"?\n\nThis will replace your current dashboard. Make sure you've exported your current work first.`
        );

        if (confirmed) {
          dispatch(importDashboard(dashboardResult.data));
          alert('Dashboard imported successfully!');
        }

        if (fileInputRef.current) {
          fileInputRef.current.value = '';
        }
        return;
      }

      // Try widget import
      const widgetResult = validateWidgetImport(json);
      if (widgetResult.success) {
        const widgetData = widgetResult.data;

        // Add widget to dashboard (new ID will be generated by addWidget action)
        dispatch(
          addWidget({
            type: widgetData.widget.type,
            layout: {
              x: 0,
              y: 0,
              w: widgetData.layout.w,
              h: widgetData.layout.h,
              minW: widgetData.layout.minW,
              minH: widgetData.layout.minH,
              maxW: widgetData.layout.maxW,
              maxH: widgetData.layout.maxH,
              locked: widgetData.layout.locked,
              noResize: widgetData.layout.noResize,
              noMove: widgetData.layout.noMove,
            },
            props: widgetData.widget.props,
          })
        );

        alert(
          `Widget imported successfully!\n\nType: ${
            widgetData.widgetType
          }\nOriginal source: ${widgetData.exportedFrom || 'Unknown'}`
        );

        if (fileInputRef.current) {
          fileInputRef.current.value = '';
        }
        return;
      }

      // Neither dashboard nor widget format
      alert(
        `Import failed: Invalid file format\n\nDashboard error: ${dashboardResult.error}\nWidget error: ${widgetResult.error}`
      );
    } catch (error) {
      alert(
        `Import failed: ${
          error instanceof Error ? error.message : 'Unknown error'
        }`
      );
      console.error('[Import] Error:', error);
    }

    // Clear file input
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleImportClick = () => {
    fileInputRef.current?.click();
  };

  return {
    fileInputRef,
    handleFileSelect,
    handleImportClick,
  };
}
